### ISSUE TITLE
multi-thread co-processors

### ISSUE THREAD

**Issue by YiRanMushroom** [AE2-UEL/Applied-Energistics-2#171]
Can you add some multi-thread co-processors that have higher efficiency than normal co-processors? because mods like extraCPUs have already add biger crafting cpu, but the co-processors are normal, and a really big place is needed to build a high-efficiency CPU.

This function has already existed in 1.7.10, added by ae2 additions, and i want a function like that.

If you don't have a future plan to do that, please reply that you don't want to add it.

**Comment by WALHAY** [comment]
I updated my fork as you ask
So you can use it 
https://github.com/GregTech-Precision/Applied-Energistics-2-Precision-Edition/releases/tag/precision-v0.54.7

**Comment by YiRanMushroom** [comment]
yeah i do think this is very important. i was now busying at my school work. i tried to code it in the past, but failed with crash problems, i didn't have that much time so i gave up.

**Comment by MicroObsidianBlock** [comment]
Hey, I saw this issue and downloaded your fork, however, I found many compatibility problems, which would probably caused by your changing the version name(you added sth like precised...). So can you update your fork to the newest version and not to change the version name(I think you can change the mod name instead).

Also, I want to make a separate version of the co-processors, so I want to ask if you are working on it. If not, I would like to ask if you mind me use/copy some of your code, I will credit you after releasomg. Because of the code of AE2, I found it difficult to do this job in a seperate mod, And I really need it because I am going to put that in my modpack. So I wonder if you can help me to do the mod, or I need to do it by myself, which seems really a hard work, cuz I have already met many problems when making it.

(My English is not good, so please don't mind some expression which is innapropriate.)

**Comment by YiRanMushroom** [comment]
It actually has some problems, I changed a little bit so it can work in some circumstances.
However, I think it really need to be updated since the version is not stable when running.

**Comment by NotMyWing** [comment]
We're not really looking forward into adding larger coprocessors into AE2 natively. You can, however, install [NAE2](https://github.com/AE2-UEL/NAE2) which has them.
